### ISSUE TITLE
Your 'Database' is loaded in synchronously

### ISSUE THREAD

**Issue by akinsho** [FAC10/week-4-zapo#68]
You require in all you JSON which is a synchronous process meaning if you had a much larger database your program would take a long time to load this does not take advantage of the asynchronous nature of node.js

**Comment by ZooeyMiller** [comment]
We asked some people about this on gitter and @eliascodes gave us some advice: <br>"Sync operations are fine if they are only being executed once on server startup. It would be different if you were requiring the json within a handler or any other code that was being executed many times"<br>&<br>"Yes. Also what i said isn't quite right. If you were requiring in your handler, you would take a performance hit the first time, but after that i think it'd be fine because node caches required files."<br>So in this instance we feel this isn't a problem.
